services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017

  mongodb:
    image: mongo:5.0
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
